/*
 * Investment Account
 *
 * This service domain handles the non-cash holdings positions for a customer, covering multiple instruments as necessary
 *
 * OpenAPI spec version: 11.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Investment.Account.Models
{
    /// <summary>
    /// Fulfill any scheduled and ad-hoc obligations under a service arrangement, most typically for a financial product or facility within Investment Account. 
    /// </summary>
    [Table("Investmentaccount")]
    [DataContract]
    public partial class InvestmentAccountFacility : IEquatable<InvestmentAccountFacility>
    {

        /// <summary>
        /// Reference to the investment account product instance
        /// </summary>
        /// <value>Reference to the investment account product instance</value>

        [DataMember(Name = "ProductInstanceReference")]
        public string ProductInstanceReference { get; set; }

        /// <summary>
        /// The investment account number in any suitable format
        /// </summary>
        /// <value>The investment account number in any suitable format</value>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [DataMember(Name="InvestmentAccountNumber")]
        public string? InvestmentAccountNumber { get; set; }

        /// <summary>
        /// Reference to the account primary party/owner
        /// </summary>
        /// <value>Reference to the account primary party/owner</value>

        [DataMember(Name="CustomerReference")]
        public string? CustomerReference { get; set; }


        /// <summary>
        /// The type of investment account (e.g. discretionary, retirement, margin, restricted instrument category - securities, off-balance sheet)
        /// </summary>
        /// <value>The type of investment account (e.g. discretionary, retirement, margin, restricted instrument category - securities, off-balance sheet)</value>

        [DataMember(Name="InvestmentAccountType")]
        public string? InvestmentAccountType { get; set; }

 
        /// <summary>
        /// The current calculated holding/position
        /// </summary>
        /// <value>The current calculated holding/position</value>

        [DataMember(Name="InstrumentPositionHolding")]
        public string? InstrumentPositionHolding { get; set; }


        /// <summary>
        /// Key dates associated with the investment account (e.g. opening date, closing date)
        /// </summary>
        /// <value>Key dates associated with the investment account (e.g. opening date, closing date)</value>

        [DataMember(Name="DateType")]
        public string? DateType { get; set; }

        /// <summary>
        /// Value of the date type
        /// </summary>
        /// <value>Value of the date type</value>

        [DataMember(Name="Date")]
        public string? Date { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InvestmentAccountFacility {\n");
            sb.Append("  ProductInstanceReference: ").Append(ProductInstanceReference).Append("\n");
            sb.Append("  InvestmentAccountNumber: ").Append(InvestmentAccountNumber).Append("\n");
            sb.Append("  CustomerReference: ").Append(CustomerReference).Append("\n");
            sb.Append("  InvestmentAccountType: ").Append(InvestmentAccountType).Append("\n");
            sb.Append("  InstrumentPositionHolding: ").Append(InstrumentPositionHolding).Append("\n");
            sb.Append("  DateType: ").Append(DateType).Append("\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InvestmentAccountFacility)obj);
        }

        /// <summary>
        /// Returns true if InvestmentAccountFacility instances are equal
        /// </summary>
        /// <param name="other">Instance of InvestmentAccountFacility to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InvestmentAccountFacility other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ProductInstanceReference == other.ProductInstanceReference ||
                    ProductInstanceReference != null &&
                    ProductInstanceReference.Equals(other.ProductInstanceReference)
                ) && 
                (
                    InvestmentAccountNumber == other.InvestmentAccountNumber ||
                    InvestmentAccountNumber != null &&
                    InvestmentAccountNumber.Equals(other.InvestmentAccountNumber)
                ) && 
                (
                    CustomerReference == other.CustomerReference ||
                    CustomerReference != null &&
                    CustomerReference.Equals(other.CustomerReference)
                ) && 
                (
                    InvestmentAccountType == other.InvestmentAccountType ||
                    InvestmentAccountType != null &&
                    InvestmentAccountType.Equals(other.InvestmentAccountType)
                ) && 
                (
                    DateType == other.DateType ||
                    DateType != null &&
                    DateType.Equals(other.DateType)
                ) && 
                (
                    Date == other.Date ||
                    Date != null &&
                    Date.Equals(other.Date)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ProductInstanceReference != null)
                    hashCode = hashCode * 59 + ProductInstanceReference.GetHashCode();
                    if (InvestmentAccountNumber != null)
                    hashCode = hashCode * 59 + InvestmentAccountNumber.GetHashCode();
                    if (CustomerReference != null)
                    hashCode = hashCode * 59 + CustomerReference.GetHashCode();
                    if (InvestmentAccountType != null)
                    hashCode = hashCode * 59 + InvestmentAccountType.GetHashCode();
                    if (DateType != null)
                    hashCode = hashCode * 59 + DateType.GetHashCode();
                    if (Date != null)
                    hashCode = hashCode * 59 + Date.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InvestmentAccountFacility left, InvestmentAccountFacility right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InvestmentAccountFacility left, InvestmentAccountFacility right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
